image: doejgi/genespace

tasks:
- name: MAIN - TERMINAL TO USE
  # Installing click and ruff in the mamba environment didn't work for some reason
  # It is much easier to install via that mamba env's pip3
  # and then install pretext-to-tpf
  command: |
    gp preview https://htmlpreview.github.io/?https://github.com/jtlovell/tutorials/blob/main/genespaceGuide.html 
    unzip Genespace.zip
    mv testGenespace/ genespace_data
    touch genespace_session.R
    clear

vscode:
  extensions:
    - cweijan.vscode-office
    - streetsidesoftware.code-spell-checker # Spelling checker for source code

workspaceLocation: "/workspace/GENESPACE"
